using FluentMigrator;

namespace Infrastructure.Persistence.Migrations;

[Migration(20230324201917)]
public class SeedCurrencyTable : Migration
{
    public override void Up()
    {
        Insert.IntoTable("currency")
            .Row(new { alphabetic_code = "AED", name = "United Arab Emirates Dirham" })
            .Row(new { alphabetic_code = "AFN", name = "Afghan Afghani" })
            .Row(new { alphabetic_code = "ALL", name = "Albanian Lek" })
            .Row(new { alphabetic_code = "AMD", name = "Armenian Dram" })
            .Row(new { alphabetic_code = "ANG", name = "Netherlands Antillean Guilder" })
            .Row(new { alphabetic_code = "AOA", name = "Angolan Kwanza" })
            .Row(new { alphabetic_code = "ARS", name = "Argentine Peso" })
            .Row(new { alphabetic_code = "AUD", name = "Australian Dollar" })
            .Row(new { alphabetic_code = "AWG", name = "Aruban Florin" })
            .Row(new { alphabetic_code = "AZN", name = "Azerbaijani Manat" })
            .Row(new { alphabetic_code = "BAM", name = "Bosnia-Herzegovina Convertible Mark" })
            .Row(new { alphabetic_code = "BBD", name = "Barbadian Dollar" })
            .Row(new { alphabetic_code = "BDT", name = "Bangladeshi Taka" })
            .Row(new { alphabetic_code = "BGN", name = "Bulgarian Lev" })
            .Row(new { alphabetic_code = "BHD", name = "Bahraini Dinar" })
            .Row(new { alphabetic_code = "BIF", name = "Burundian Franc" })
            .Row(new { alphabetic_code = "BMD", name = "Bermudan Dollar" })
            .Row(new { alphabetic_code = "BND", name = "Brunei Dollar" })
            .Row(new { alphabetic_code = "BOB", name = "Bolivian Boliviano" })
            .Row(new { alphabetic_code = "BRL", name = "Brazilian Real" })
            .Row(new { alphabetic_code = "BSD", name = "Bahamian Dollar" })
            .Row(new { alphabetic_code = "BTC", name = "Bitcoin" })
            .Row(new { alphabetic_code = "BTN", name = "Bhutanese Ngultrum" })
            .Row(new { alphabetic_code = "BWP", name = "Botswanan Pula" })
            .Row(new { alphabetic_code = "BYN", name = "Belarusian Ruble" })
            .Row(new { alphabetic_code = "BZD", name = "Belize Dollar" })
            .Row(new { alphabetic_code = "CAD", name = "Canadian Dollar" })
            .Row(new { alphabetic_code = "CDF", name = "Congolese Franc" })
            .Row(new { alphabetic_code = "CHF", name = "Swiss Franc" })
            .Row(new { alphabetic_code = "CLF", name = "Chilean Unit of Account (UF)" })
            .Row(new { alphabetic_code = "CLP", name = "Chilean Peso" })
            .Row(new { alphabetic_code = "CNH", name = "Chinese Yuan (Offshore)" })
            .Row(new { alphabetic_code = "CNY", name = "Chinese Yuan" })
            .Row(new { alphabetic_code = "COP", name = "Colombian Peso" })
            .Row(new { alphabetic_code = "CRC", name = "Costa Rican Colón" })
            .Row(new { alphabetic_code = "CUC", name = "Cuban Convertible Peso" })
            .Row(new { alphabetic_code = "CUP", name = "Cuban Peso" })
            .Row(new { alphabetic_code = "CVE", name = "Cape Verdean Escudo" })
            .Row(new { alphabetic_code = "CZK", name = "Czech Koruna" })
            .Row(new { alphabetic_code = "DJF", name = "Djiboutian Franc" })
            .Row(new { alphabetic_code = "DKK", name = "Danish Krone" })
            .Row(new { alphabetic_code = "DOP", name = "Dominican Peso" })
            .Row(new { alphabetic_code = "DZD", name = "Algerian Dinar" })
            .Row(new { alphabetic_code = "EGP", name = "Egyptian Pound" })
            .Row(new { alphabetic_code = "ERN", name = "Eritrean Nakfa" })
            .Row(new { alphabetic_code = "ETB", name = "Ethiopian Birr" })
            .Row(new { alphabetic_code = "EUR", name = "Euro" })
            .Row(new { alphabetic_code = "FJD", name = "Fijian Dollar" })
            .Row(new { alphabetic_code = "FKP", name = "Falkland Islands Pound" })
            .Row(new { alphabetic_code = "GBP", name = "British Pound Sterling" })
            .Row(new { alphabetic_code = "GEL", name = "Georgian Lari" })
            .Row(new { alphabetic_code = "GHS", name = "Ghanaian Cedi" })
            .Row(new { alphabetic_code = "GIP", name = "Gibraltar Pound" })
            .Row(new { alphabetic_code = "GMD", name = "Gambian Dalasi" })
            .Row(new { alphabetic_code = "GNF", name = "Guinean Franc" })
            .Row(new { alphabetic_code = "GTQ", name = "Guatemalan Quetzal" })
            .Row(new { alphabetic_code = "GYD", name = "Guyanaese Dollar" })
            .Row(new { alphabetic_code = "HKD", name = "Hong Kong Dollar" })
            .Row(new { alphabetic_code = "HNL", name = "Honduran Lempira" })
            .Row(new { alphabetic_code = "HRK", name = "Croatian Kuna" })
            .Row(new { alphabetic_code = "HTG", name = "Haitian Gourde" })
            .Row(new { alphabetic_code = "HUF", name = "Hungarian Forint" })
            .Row(new { alphabetic_code = "IDR", name = "Indonesian Rupiah" })
            .Row(new { alphabetic_code = "ILS", name = "Israeli New Sheqel" })
            .Row(new { alphabetic_code = "INR", name = "Indian Rupee" })
            .Row(new { alphabetic_code = "IQD", name = "Iraqi Dinar" })
            .Row(new { alphabetic_code = "IRR", name = "Iranian Rial" })
            .Row(new { alphabetic_code = "ISK", name = "Icelandic Króna" })
            .Row(new { alphabetic_code = "JMD", name = "Jamaican Dollar" })
            .Row(new { alphabetic_code = "JOD", name = "Jordanian Dinar" })
            .Row(new { alphabetic_code = "JPY", name = "Japanese Yen" })
            .Row(new { alphabetic_code = "KES", name = "Kenyan Shilling" })
            .Row(new { alphabetic_code = "KGS", name = "Kyrgyzstani Som" })
            .Row(new { alphabetic_code = "KHR", name = "Cambodian Riel" })
            .Row(new { alphabetic_code = "KMF", name = "Comorian Franc" })
            .Row(new { alphabetic_code = "KPW", name = "North Korean Won" })
            .Row(new { alphabetic_code = "KRW", name = "South Korean Won" })
            .Row(new { alphabetic_code = "KWD", name = "Kuwaiti Dinar" })
            .Row(new { alphabetic_code = "KYD", name = "Cayman Islands Dollar" })
            .Row(new { alphabetic_code = "KZT", name = "Kazakhstani Tenge" })
            .Row(new { alphabetic_code = "LAK", name = "Lao Kip" })
            .Row(new { alphabetic_code = "LBP", name = "Lebanese Pound" })
            .Row(new { alphabetic_code = "LKR", name = "Sri Lankan Rupee" })
            .Row(new { alphabetic_code = "LRD", name = "Liberian Dollar" })
            .Row(new { alphabetic_code = "LSL", name = "Lesotho Loti" })
            .Row(new { alphabetic_code = "LYD", name = "Libyan Dinar" })
            .Row(new { alphabetic_code = "MAD", name = "Moroccan Dirham" })
            .Row(new { alphabetic_code = "MDL", name = "Moldovan Leu" })
            .Row(new { alphabetic_code = "MGA", name = "Malagasy Ariary" })
            .Row(new { alphabetic_code = "MKD", name = "Macedonian Denar" })
            .Row(new { alphabetic_code = "MMK", name = "Myanmar Kyat" })
            .Row(new { alphabetic_code = "MNT", name = "Mongolian Tugrik" })
            .Row(new { alphabetic_code = "MOP", name = "Macau Pataca" })
            .Row(new { alphabetic_code = "MRO", name = "Mauritanian Ouguiya" })
            .Row(new { alphabetic_code = "MRU", name = "Mauritanian Ouguiya" })
            .Row(new { alphabetic_code = "MUR", name = "Mauritian Rupee" })
            .Row(new { alphabetic_code = "MVR", name = "Maldivian Rufiyaa" })
            .Row(new { alphabetic_code = "MWK", name = "Malawian Kwacha" })
            .Row(new { alphabetic_code = "MXN", name = "Mexican Peso" })
            .Row(new { alphabetic_code = "MYR", name = "Malaysian Ringgit" })
            .Row(new { alphabetic_code = "MZN", name = "Mozambican Metical" })
            .Row(new { alphabetic_code = "NAD", name = "Namibian Dollar" })
            .Row(new { alphabetic_code = "NGN", name = "Nigerian Naira" })
            .Row(new { alphabetic_code = "NIO", name = "Nicaraguan Cordoba" })
            .Row(new { alphabetic_code = "NOK", name = "Norwegian Krone" })
            .Row(new { alphabetic_code = "NPR", name = "Nepalese Rupee" })
            .Row(new { alphabetic_code = "NZD", name = "New Zealand Dollar" })
            .Row(new { alphabetic_code = "OMR", name = "Omani Rial" })
            .Row(new { alphabetic_code = "PAB", name = "Panamanian Balboa" })
            .Row(new { alphabetic_code = "PEN", name = "Peruvian Sol" })
            .Row(new { alphabetic_code = "PGK", name = "Papua New Guinean Kina" })
            .Row(new { alphabetic_code = "PHP", name = "Philippine Peso" })
            .Row(new { alphabetic_code = "PKR", name = "Pakistani Rupee" })
            .Row(new { alphabetic_code = "PLN", name = "Polish Zloty" })
            .Row(new { alphabetic_code = "PYG", name = "Paraguayan Guarani" })
            .Row(new { alphabetic_code = "QAR", name = "Qatari Rial" })
            .Row(new { alphabetic_code = "RON", name = "Romanian Leu" })
            .Row(new { alphabetic_code = "RSD", name = "Serbian Dinar" })
            .Row(new { alphabetic_code = "RUB", name = "Russian Ruble" })
            .Row(new { alphabetic_code = "RWF", name = "Rwandan Franc" })
            .Row(new { alphabetic_code = "SAR", name = "Saudi Arabian Riyal" })
            .Row(new { alphabetic_code = "SBD", name = "Solomon Islands Dollar" })
            .Row(new { alphabetic_code = "SCR", name = "Seychellois Rupee" })
            .Row(new { alphabetic_code = "SDG", name = "Sudanese Pound" })
            .Row(new { alphabetic_code = "SEK", name = "Swedish Krona" })
            .Row(new { alphabetic_code = "SGD", name = "Singapore Dollar" })
            .Row(new { alphabetic_code = "SHP", name = "Saint Helena Pound" })
            .Row(new { alphabetic_code = "SLL", name = "Sierra Leonean Leone" })
            .Row(new { alphabetic_code = "SOS", name = "Somali Shilling" })
            .Row(new { alphabetic_code = "SRD", name = "Surinamese Dollar" })
            .Row(new { alphabetic_code = "SSP", name = "South Sudanese Pound" })
            .Row(new { alphabetic_code = "STD", name = "São Tomé and Príncipe Dobra" })
            .Row(new { alphabetic_code = "SVC", name = "Salvadoran Colón" })
            .Row(new { alphabetic_code = "SYP", name = "Syrian Pound" })
            .Row(new { alphabetic_code = "SZL", name = "Swazi Lilangeni" })
            .Row(new { alphabetic_code = "THB", name = "Thai Baht" })
            .Row(new { alphabetic_code = "TJS", name = "Tajikistani Somoni" })
            .Row(new { alphabetic_code = "TMT", name = "Turkmenistani Manat" })
            .Row(new { alphabetic_code = "TND", name = "Tunisian Dinar" })
            .Row(new { alphabetic_code = "TOP", name = "Tongan Pa'anga" })
            .Row(new { alphabetic_code = "TRY", name = "Turkish Lira" })
            .Row(new { alphabetic_code = "TTD", name = "Trinidad and Tobago Dollar" })
            .Row(new { alphabetic_code = "TWD", name = "New Taiwan Dollar" })
            .Row(new { alphabetic_code = "TZS", name = "Tanzanian Shilling" })
            .Row(new { alphabetic_code = "UAH", name = "Ukrainian Hryvnia" })
            .Row(new { alphabetic_code = "UGX", name = "Ugandan Shilling" })
            .Row(new { alphabetic_code = "USD", name = "United States Dollar" })
            .Row(new { alphabetic_code = "UYU", name = "Uruguayan Peso" })
            .Row(new { alphabetic_code = "UZS", name = "Uzbekistani Som" })
            .Row(new { alphabetic_code = "VES", name = "Venezuelan Bolívar Soberano" })
            .Row(new { alphabetic_code = "VND", name = "Vietnamese Dong" })
            .Row(new { alphabetic_code = "VUV", name = "Vanuatu Vatu" })
            .Row(new { alphabetic_code = "WST", name = "Samoan Tala" })
            .Row(new { alphabetic_code = "XAF", name = "Central African CFA Franc" })
            .Row(new { alphabetic_code = "XCD", name = "East Caribbean Dollar" })
            .Row(new { alphabetic_code = "XDR", name = "Special Drawing Rights" })
            .Row(new { alphabetic_code = "XOF", name = "West African CFA Franc" })
            .Row(new { alphabetic_code = "XPF", name = "CFP Franc" })
            .Row(new { alphabetic_code = "YER", name = "Yemeni Rial" })
            .Row(new { alphabetic_code = "ZAR", name = "South African Rand" })
            .Row(new { alphabetic_code = "ZMW", name = "Zambian Kwacha" })
            .Row(new { alphabetic_code = "ZWL", name = "Zimbabwean Dollar" });
    }

    public override void Down() => Delete.FromTable("currency").AllRows();
}