name: Deploy Acquiring Bank Simulator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore "Acquiring Bank Simulator/Acquiring Bank Simulator API.csproj"

    - name: Build
      run: dotnet build "Acquiring Bank Simulator/Acquiring Bank Simulator API.csproj" --configuration Release --no-restore

    - name: Publish
      run: dotnet publish "Acquiring Bank Simulator/Acquiring Bank Simulator API.csproj" --configuration Release --no-build --output ./build_output

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Generate deployment package
      run: zip -r deploy.zip ./Acquiring Bank Simulator/ -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Acquiring Bank Simulator
        environment_name: Acquiringbanksimulator-env
        version_label: 12345
        region: us-east-1
        deployment_package: deploy.zip