name: Tests

on: push

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Test Projects
        run: |
          echo github.ref
          dotnet test